<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = [
        'Japanese',
        'Chinese',
        'English',
        'Hindi',
        'Spanish',
        'Arabic',
        'Portuguese',
        'Bengali',
        'Russian',
        'Urdu',
        'Indonesian',
        'German',
        'French',
        'Swahili',
        'Turkish',
        'Korean',
        'Italian',
        'Vietnamese',
        'Tamil',
        'Filipino (Tagalog)',
        'Marathi',
        'Punjabi',
        'Polish',
        'Ukrainian',
        'Malayalam',
        'Yoruba',
        'Maithili',
        'Uzbek',
        'Farsi',
        'Mandarin',
        'Acehnese',
        'Acholi',
        'Afar',
        'Afrikaans',
        'Akan',
        'Albanian',
        'Amharic',
        'Anlo',
        'Aramaic',
        'Armenian',
        'Askunu',
        'Assamese',
        'Azerbaijani',
        'Badini',
        'Balinese',
        'Balochi',
        'Bangla',
        'Banyuwangi',
        'Batak',
        'Beja',
        'Belarusian',
        'Bemba',
        'Bislama',
        'Bosnian',
        'Brahui',
        'Bravanese',
        'Buginese',
        'Bulgarian',
        'Burmese',
        'Cantonese',
        'Catalan',
        'Cebuano',
        'Chichewa (Nyanja)',
        'Chinese',
        'Croatian',
        'Comorian',
        'Czech',
        'Danish',
        'Dari',
        'Dioula',
        'Dyula',
        'Dutch',
        'Edo',
        'Estonian',
        'Ewe',
        'Farsi',
        'Fataluku',
        'Fijian',
        'Filipino (Tagalog)',
        'Finnish',
        'Flemish',
        'French',
        'Fujianese',
        'Fulani',
        'Fur',
        'Ga',
        'Gaelic',
        'Galician',
        'Gan',
        'Georgian',
        'German',
        'Ghanaian',
        'Gibanawa',
        'Gikuyu',
        'Gilaki',
        'Greek',
        'Guarani',
        'Gujarati',
        'Gullah',
        'Haitian Creole',
        'Hakka',
        'Hausa',
        'Hazaragi',
        'Hebrew',
        'Herero',
        'Hiligaynon',
        'Hindi',
        'Hindko',
        'Hindustani',
        'Hmar',
        'Hmong',
        'Hokkien',
        'Hungarian',
        'Hwla',
        'Icelandic',
        'Igbo (Ibo)',
        'Ilokano',
        'Ilonggo',
        'Imeraguen',
        'Indian',
        'Indonesian',
        'Inuktitut',
        'Ishkashimi',
        'Italian',
        'Iu Mien',
        'Jamaican Creole',
        'Japanese',
        'Javanese',
        'Kalasha-ala',
        'Kamba',
        'Kamkata-vari',
        'Kannada',
        'Kanuri',
        'Kapampangan',
        'Kara',
        'Karay-a',
        'Karenic',
        'Kashmiri',
        'Kazakh',
        'Khmer (Cambodian)',
        'Kikuyu',
        'Kinyarwanda',
        'Korobore',
        'Krio',
        'Kirundi',
        'Kongo',
        'Konkani',
        'Korean',
        'Kosovan',
        'Kujarge',
        'Kunama',
        'Kurdish',
        'Kurmanji',
        'Kyrgyz',
        'Laal',
        'Latvian',
        'Lao',
        'Liberian',
        'Lingala',
        'Lithuanian',
        'Lombard',
        'Lufu',
        'Luganda',
        'Luo (Dholuo)',
        'Luri',
        'Lusoga',
        'Luyia',
        'Maay Maay',
        'Macedonian',
        'Madurese',
        'Maithili',
        'Makhuwa',
        'Malagasy',
        'Malay',
        'Malayalam',
        'Malaysian',
        'Malinke',
        'Maltese',
        'Mandarin',
        'Mandingo',
        'Mandinka',
        'Maninka',
        'Manipuri',
        'Marathi',
        'Marshallese',
        'Mauritian Creole',
        'Mawa',
        'Mazanderani',
        'Meitei',
        'Mende',
        'Min',
        'Minangkabau',
        'Mirpuri',
        'Mizo',
        'Moldovan',
        'Mongolian',
        'Montenegrin',
        'Moroccan',
        'Munji',
        'Nara',
        'Ndali',
        'Ndebele',
        'Neapolitan',
        'Nemadi',
        'Nepali',
        'Northern Sotho',
        'Nuer',
        'Norwegian',
        'Nuosu',
        'Nuristani',
        'Nyakyusa',
        'Oriya',
        'Oromo',
        'Pahari',
        'Pahari-Pothwari',
        'Paite',
        'Pakistani',
        'Pali',
        'Papiamento',
        'Pashto (Pushto)',
        'Pashayi',
        'Peul',
        'Patois',
        'Persian',
        'Piemonteis',
        'Polish',
        'Portuguese',
        'Pothohari',
        'Punjabi',
        'Quechua',
        'Qusqu-Qullaw',
        'Rer Bare',
        'Roma',
        'Romani',
        'Romanian',
        'Russian',
        'Runyankole',
        'Saho',
        'Sahu',
        'Samburu',
        'Sango',
        'Santali',
        'Saraiki',
        'Serbian',
        'Serbo-Croatian',
        'Serer',
        'Sesotho',
        'Shan',
        'Shanghainese',
        'Shona',
        'Shughni',
        'Sindhi',
        'Sinhalese',
        'Sininkere',
        'Slovak',
        'Slovenian',
        'Somali',
        'Sorani',
        'South Bolivian Quechua',
        'Spanish',
        'Sukuma',
        'Susu',
        'Sudanese',
        'Sundanese',
        'Swahili',
        'Swati',
        'Swedish',
        'Tagalog',
        'Taishan',
        'Taiwanese',
        'Tajik',
        'Tamazight',
        'Tamil',
        'Tatar',
        'Tebu',
        'Teluga',
        'Telugu',
        'Temmne',
        'Tetum',
        'Thai',
        'Tibetan',
        'Tigre',
        'Tigrinya',
        'Tregami',
        'Tshil',
        'Tshiluba',
        'Tsonga',
        'Tswana',
        'Turkish',
        'Turkmen',
        'Twi',
        'Ukrainian',
        'Umbundu',
        'Urdu',
        'Uyghur',
        'Uzbek',
        'Vietnamese',
        'Wakhi',
        'Waray-Waray',
        'Wasi-wari',
        'Welsh',
        'Weyto',
        'Wolof',
        'Wu',
        'Wutana',
        'Xhosa',
        'Yauma',
        'Yeni',
        'Yi',
        'Yiddish',
        'Yoruba',
        'Zaghawa',
        'Zaza',
        'Zhuang',
        'Zulu'

];

foreach ($languages as $language) {
    DB::table('languages')->insert([
        'name' => $language,
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
    ]);
}
    }
}
